ALTER TABLE brands
    ADD COLUMN auto_id BIGINT UNSIGNED DEFAULT NULL NULL;
ALTER TABLE vehicles
    ADD COLUMN auto_id BIGINT UNSIGNED DEFAULT NULL NULL;
ALTER TABLE modifications
    ADD COLUMN auto_id BIGINT UNSIGNED DEFAULT NULL NULL;